name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '13 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: bash build.sh

      - name: Test Docker image
        run: bash test.sh

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ghcr.io
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Publish the Docker image
        run: source variables.sh && docker push $DOCKER_IMAGE:latest
        if: ${{ github.ref == 'refs/heads/main' }}
